version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: ${MYSQL_DB_HOST}
      JOOMLA_DB_USER: ${MYSQL_DB_PASSWORD}
      JOOMLA_DB_PASSWORD: ${MYSQL_DB_USER}
      JOOMLA_DB_NAME: ${MYSQL_DB_NAME}
    volumes:
      - type: bind
        source: /mnt/efs
        target: /var/www/html

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin